// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// Injectors from wire.go:

// InitializeApp initializes the entire application with all dependencies
func InitializeApp() (*AppContainer, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	logger, err := ProvideLogger()
	if err != nil {
		return nil, err
	}
	jwtService := ProvideJWTService(config)
	db, err := ProvideDatabase(config)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(db)
	refreshTokenRepository := ProvideRefreshTokenRepository(db)
	passwordHasher := ProvidePasswordHasher(config)
	customValidator := ProvideValidator()
	authService := ProvideAuthService(userRepository, refreshTokenRepository, passwordHasher, jwtService, customValidator, config)
	authHandler := ProvideAuthHandler(authService)
	postRepository := ProvidePostRepository(db)
	storage := ProvideStorage(config)
	validator := ProvideImageValidator(config)
	processor := ProvideImageProcessor()
	userService := ProvideUserService(userRepository, postRepository, passwordHasher, customValidator, storage, validator, processor)
	userHandler := ProvideUserHandler(userService)
	categoryRepository := ProvideCategoryRepository(db)
	categoryService := ProvideCategoryService(categoryRepository, postRepository, customValidator)
	categoryHandler := ProvideCategoryHandler(categoryService)
	commentRepository := ProvideCommentRepository(db)
	sanitizer := ProvideSanitizer()
	postService := ProvidePostService(postRepository, categoryRepository, commentRepository, sanitizer, customValidator)
	postHandler := ProvidePostHandler(postService)
	commentService := ProvideCommentService(commentRepository, postRepository, sanitizer, customValidator)
	commentHandler := ProvideCommentHandler(commentService)
	mediaRepository := ProvideMediaRepository(db)
	mediaService := ProvideMediaService(mediaRepository, postRepository, storage, validator, processor, customValidator)
	mediaHandler := ProvideMediaHandler(mediaService)
	router := ProvideRouter(config, logger, jwtService, userRepository, authHandler, userHandler, categoryHandler, postHandler, commentHandler, mediaHandler)
	appContainer := ProvideAppContainer(router, db, logger)
	return appContainer, nil
}
